spring:
  application:
    name: spring-batch-integration-sample
  batch:
    job:
      enabled: false
  rabbitmq:
    host: 192.168.13.229
    port: 5672
    username: hengyun
    password: hengyun
    virtual-host: hengyun
    publisher-confirm-type: simple
    publisher-returns: false
    requested-channel-max: 2047
    template:
      exchange: defaultExchange
      routing-key: defaultRoutingKey
      mandatory: true # 交换机(Exchange)无法匹配到队列(queue). True:返回到生产者队列; False:直接丢弃.
      receive-timeout: 10000ms
      reply-timeout: 10000ms
      retry:
        enabled: true
        max-interval: 1000ms
        multiplier: 1

thread:
  pool:
    core-size: 8
    max-size: 12
    keepalive-time: 60